services:
  iris:
    container_name: esb
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - default
    ports:
      - 9092:52773 # Management Portal / REST API
      - 9091:1972 # SuperServer port

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    depends_on:
      - iris
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - default
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - default
    restart: unless-stopped

networks:
  default:
    driver: bridge